[package]
name = "backtester2"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
polars = "0.46.0"
polars-io = { version = "0.46.0", features = ["parquet"] }
polars-core = "0.46.0"

